site_name: Programación
repo_url: https://github.com/martipatgra/programacion2122
nav:
    - Inicio: index.md
    - Sobre : about.md
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: teal
  
