site_name: Programación
nav:
    - Inicio: index.md
    - Sobre : about.md
theme:
  name: material
  language: es
  #custom_dir: overrides
  #logo: assets/logo.png
  palette:
    primary: teal
  extra:
    generator: false
  copyright: Copyright &copy; 2021 - Patricia Martí
  
