site_name: Programación
repo_url: https://github.com/martipatgra/programacion2122
nav:
    - Inicio: index.md
    - Sobre : about.md
theme:
  name: material
  language: es
  #custom_dir: overrides
  #logo: assets/logo.png
  palette:
    primary: teal
  extra:
    generator: false
    social:
        - icon: none
        - link: none
        - name: none
  copyright: Copyright &copy; 2021 - Patricia Martí
  
